language: python

python:
  - 3.6

install:
  - "pip install pip==18.1"
  - "pip install poetry==0.12.10"
  - "poetry install --no-interaction"
  - "poetry shell"

jobs:
  include:
    - stage: codestyle
      python: 3.6
      script:
        - "make lint"
    - stage: test
      python: 3.6
      script:
        - "make test"
    - stage: coverage
      python: 3.6
      script:
        - "make coverage"
