language: python

python:
  - 3.6

install:
  - "pip install -U pip"
  - "pip install poetry"
  - "poetry install -E tf --no-interaction --no-ansi"

jobs:
  include:
    - stage: codestyle
      python: 3.6
      script:
        - "make lint"
    - stage: test
      python: 3.6
      script:
        - "make test"
    - stage: coverage
      python: 3.6
      script:
        - "make coverage"
