from .abstract import Grammeme
from .animacy import Animacy
from .aspect import Aspect
from .case import Case
from .degree import Degree
from .gender import Gender
from .mood import Mood
from .number import Number
from .numform import NumericalForm
from .person import Person
from .pos import PartOfSpeech
from .tense import Tense
from .variant import Variant
from .verbform import VerbForm
from .voice import Voice
