from .abstract import Grammeme  # noqa: F401
from .animacy import Animacy  # noqa: F401
from .aspect import Aspect  # noqa: F401
from .case import Case  # noqa: F401
from .degree import Degree  # noqa: F401
from .gender import Gender  # noqa: F401
from .mood import Mood  # noqa: F401
from .number import Number  # noqa: F401
from .numform import NumericalForm  # noqa: F401
from .person import Person  # noqa: F401
from .pos import PartOfSpeech  # noqa: F401
from .tense import Tense  # noqa: F401
from .variant import Variant  # noqa: F401
from .verbform import VerbForm  # noqa: F401
from .voice import Voice  # noqa: F401
