from .animacy import get_animacy
from .aspect import get_aspect
from .case import get_case
from .degree import get_degree
from .gender import get_gender
from .mood import get_mood
from .number import get_number
from .person import get_person
from .pos import get_part_of_speech
from .tense import get_tense
from .verbform import get_verbform
from .voice import get_voice
